//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class boletoguia
    {
        public string usuario { get; set; }
        public string computer { get; set; }
        public int sid { get; set; }
        public short seq { get; set; }
        public string codreduzido { get; set; }
        public string nome { get; set; }
        public string cpf { get; set; }
        public string endereco { get; set; }
        public Nullable<short> numimovel { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string uf { get; set; }
        public string fulllanc { get; set; }
        public string numdoc { get; set; }
        public Nullable<short> numparcela { get; set; }
        public Nullable<short> totparcela { get; set; }
        public Nullable<System.DateTime> datavencto { get; set; }
        public string numdoc2 { get; set; }
        public string digitavel { get; set; }
        public string codbarra { get; set; }
        public Nullable<decimal> valorguia { get; set; }
        public string obs { get; set; }
        public string numproc { get; set; }
        public string cep { get; set; }
        public string numbarra2a { get; set; }
        public string numbarra2b { get; set; }
        public string numbarra2c { get; set; }
        public string numbarra2d { get; set; }
        public string desclanc { get; set; }
    }
}
