//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class cadimob
    {
        public int codreduzido { get; set; }
        public short dv { get; set; }
        public int codcondominio { get; set; }
        public short distrito { get; set; }
        public short setor { get; set; }
        public short quadra { get; set; }
        public int lote { get; set; }
        public short seq { get; set; }
        public short unidade { get; set; }
        public short subunidade { get; set; }
        public Nullable<short> li_num { get; set; }
        public string li_compl { get; set; }
        public string li_cep { get; set; }
        public string li_uf { get; set; }
        public Nullable<short> li_codcidade { get; set; }
        public Nullable<short> li_codbairro { get; set; }
        public string li_quadras { get; set; }
        public string li_lotes { get; set; }
        public Nullable<decimal> dt_areaterreno { get; set; }
        public Nullable<short> dt_codusoterreno { get; set; }
        public Nullable<short> dt_codbenf { get; set; }
        public Nullable<short> dt_codtopog { get; set; }
        public Nullable<short> dt_codcategprop { get; set; }
        public Nullable<short> dt_codsituacao { get; set; }
        public Nullable<short> dt_codpedol { get; set; }
        public string dt_numagua { get; set; }
        public Nullable<decimal> dt_fracaoideal { get; set; }
        public Nullable<short> dc_qtdeedif { get; set; }
        public Nullable<short> dc_qtdepav { get; set; }
        public Nullable<short> ee_tipoend { get; set; }
        public Nullable<bool> inativo { get; set; }
        public string tipomat { get; set; }
        public Nullable<long> nummat { get; set; }
        public Nullable<System.DateTime> datainclusao { get; set; }
        public Nullable<bool> imune { get; set; }
        public Nullable<bool> conjugado { get; set; }
        public Nullable<bool> resideimovel { get; set; }
        public Nullable<bool> cip { get; set; }
    
        public virtual bairro bairro { get; set; }
        public virtual condominio condominio { get; set; }
        public virtual facequadra facequadra { get; set; }
        public virtual endentrega endentrega { get; set; }
    }
}
