//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class cep
    {
        public int codlogr { get; set; }
        public int cep1 { get; set; }
        public int valor1 { get; set; }
        public int valor2 { get; set; }
        public bool impar { get; set; }
        public bool par { get; set; }
        public Nullable<short> codbairro { get; set; }
    }
}
