//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class cidadao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cidadao()
        {
            this.mobiliarioproprietario = new HashSet<mobiliarioproprietario>();
        }
    
        public int codcidadao { get; set; }
        public string nomecidadao { get; set; }
        public string cpf { get; set; }
        public string cnpj { get; set; }
        public Nullable<int> codlogradouro { get; set; }
        public Nullable<short> numimovel { get; set; }
        public string complemento { get; set; }
        public Nullable<short> codbairro { get; set; }
        public Nullable<short> codcidade { get; set; }
        public string siglauf { get; set; }
        public Nullable<int> cep { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public string rg { get; set; }
        public string nomelogradouro { get; set; }
        public string orgao { get; set; }
        public string nomecidade { get; set; }
        public string nomebairro { get; set; }
        public string nomeuf { get; set; }
        public Nullable<bool> juridica { get; set; }
        public string pais { get; set; }
        public Nullable<int> codlogradouro2 { get; set; }
        public Nullable<short> numimovel2 { get; set; }
        public string complemento2 { get; set; }
        public Nullable<short> codbairro2 { get; set; }
        public Nullable<short> codcidade2 { get; set; }
        public string siglauf2 { get; set; }
        public Nullable<int> cep2 { get; set; }
        public string nomelogradouro2 { get; set; }
        public string etiqueta { get; set; }
        public string pais2 { get; set; }
        public string telefone2 { get; set; }
        public string email2 { get; set; }
        public string etiqueta2 { get; set; }
        public Nullable<System.DateTime> data_nascimento { get; set; }
        public string profissao { get; set; }
        public Nullable<int> codprofissao { get; set; }
        public Nullable<int> codpais { get; set; }
        public Nullable<int> codpais2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mobiliarioproprietario> mobiliarioproprietario { get; set; }
    }
}
