//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class cnaesubclasse
    {
        public string secao { get; set; }
        public int divisao { get; set; }
        public int grupo { get; set; }
        public int classe { get; set; }
        public int subclasse { get; set; }
        public string descricao { get; set; }
    }
}
