//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class comercio_eletronico
    {
        public int numdoc { get; set; }
        public string nossonumero { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> dataemissao { get; set; }
        public string nome { get; set; }
        public string cpfcnpj { get; set; }
        public string endereco { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string uf { get; set; }
        public Nullable<int> cep { get; set; }
        public Nullable<System.DateTime> datavencto { get; set; }
        public Nullable<decimal> valorguia { get; set; }
    }
}
