//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class condominio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public condominio()
        {
            this.cadimob = new HashSet<cadimob>();
        }
    
        public int cd_codigo { get; set; }
        public string cd_nomecond { get; set; }
        public short cd_distrito { get; set; }
        public short cd_setor { get; set; }
        public short cd_quadra { get; set; }
        public int cd_lote { get; set; }
        public short cd_seq { get; set; }
        public Nullable<short> cd_num { get; set; }
        public string cd_compl { get; set; }
        public string cd_uf { get; set; }
        public short cd_codcidade { get; set; }
        public short cd_codbairro { get; set; }
        public string cd_cep { get; set; }
        public string cd_quadras { get; set; }
        public string cd_lotes { get; set; }
        public Nullable<decimal> cd_areaterreno { get; set; }
        public short cd_codusoterreno { get; set; }
        public short cd_codbenf { get; set; }
        public short cd_codtopog { get; set; }
        public short cd_codcategprop { get; set; }
        public short cd_codsituacao { get; set; }
        public short cd_codpedol { get; set; }
        public Nullable<decimal> cd_areatotconstr { get; set; }
        public Nullable<short> cd_numunid { get; set; }
        public Nullable<int> cd_prop { get; set; }
        public Nullable<decimal> cd_fracao { get; set; }
    
        public virtual bairro bairro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cadimob> cadimob { get; set; }
        public virtual facequadra facequadra { get; set; }
    }
}
