//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class debitoparcela
    {
        public int codreduzido { get; set; }
        public short anoexercicio { get; set; }
        public short codlancamento { get; set; }
        public short seqlancamento { get; set; }
        public byte numparcela { get; set; }
        public byte codcomplemento { get; set; }
        public Nullable<byte> statuslanc { get; set; }
        public Nullable<System.DateTime> datavencimento { get; set; }
        public Nullable<System.DateTime> datadebase { get; set; }
        public Nullable<short> codmoeda { get; set; }
        public Nullable<int> numerolivro { get; set; }
        public Nullable<int> paginalivro { get; set; }
        public Nullable<int> numcertidao { get; set; }
        public Nullable<System.DateTime> datainscricao { get; set; }
        public Nullable<System.DateTime> dataajuiza { get; set; }
        public Nullable<decimal> valorjuros { get; set; }
        public string numprocesso { get; set; }
        public Nullable<bool> intacto { get; set; }
        public Nullable<bool> notificado { get; set; }
        public string usuario { get; set; }
        public Nullable<int> numexecfiscal { get; set; }
        public Nullable<short> anoexecfiscal { get; set; }
        public string processocnj { get; set; }
        public Nullable<bool> simplesnacional { get; set; }
        public Nullable<int> protesto_nro_titulo { get; set; }
        public Nullable<System.DateTime> protesto_data_remessa { get; set; }
    }
}
