//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class debitotributo
    {
        public int codreduzido { get; set; }
        public short anoexercicio { get; set; }
        public short codlancamento { get; set; }
        public short seqlancamento { get; set; }
        public byte numparcela { get; set; }
        public byte codcomplemento { get; set; }
        public short codtributo { get; set; }
        public Nullable<decimal> valortributo { get; set; }
        public Nullable<decimal> valorcorrecao { get; set; }
        public Nullable<decimal> valormulta { get; set; }
        public Nullable<decimal> valorjuros { get; set; }
        public Nullable<bool> intacto { get; set; }
        public Nullable<bool> valorporbaixa { get; set; }
    }
}
