//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEmpresa
    {
        public int sid { get; set; }
        public string nome { get; set; }
        public string valor { get; set; }
        public Nullable<int> principal { get; set; }
    }
}
