//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class endentrega
    {
        public int codreduzido { get; set; }
        public Nullable<int> ee_codlog { get; set; }
        public string ee_nomelog { get; set; }
        public Nullable<short> ee_numimovel { get; set; }
        public string ee_complemento { get; set; }
        public string ee_uf { get; set; }
        public Nullable<short> ee_cidade { get; set; }
        public Nullable<short> ee_bairro { get; set; }
        public string ee_cep { get; set; }
        public Nullable<short> ee_loteamento { get; set; }
        public string ee_descbairro { get; set; }
    
        public virtual bairro bairro { get; set; }
        public virtual cadimob cadimob { get; set; }
    }
}
