//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class escritoriocontabil
    {
        public short codigoesc { get; set; }
        public Nullable<int> codigoold { get; set; }
        public string nomeesc { get; set; }
        public Nullable<int> codlogradouro { get; set; }
        public string nomelogradouro { get; set; }
        public Nullable<int> numero { get; set; }
        public Nullable<short> codbairro { get; set; }
        public string nomebairro { get; set; }
        public string cep { get; set; }
        public string nomecidade { get; set; }
        public string uf { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public Nullable<bool> recebecarne { get; set; }
        public string crc { get; set; }
        public string rg { get; set; }
        public string cpf { get; set; }
        public string cnpj { get; set; }
        public Nullable<int> im { get; set; }
        public string complemento { get; set; }
    }
}
