//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class facequadra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public facequadra()
        {
            this.cadimob = new HashSet<cadimob>();
            this.condominio = new HashSet<condominio>();
        }
    
        public short coddistrito { get; set; }
        public short codsetor { get; set; }
        public short codquadra { get; set; }
        public short codface { get; set; }
        public Nullable<int> codlogr { get; set; }
        public Nullable<short> codagrupa { get; set; }
        public Nullable<byte> pavimento { get; set; }
        public string quadras { get; set; }
        public Nullable<short> codagrupanovo { get; set; }
        public string alterado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cadimob> cadimob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<condominio> condominio { get; set; }
    }
}
