//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class laseriptu
    {
        public short ano { get; set; }
        public int codreduzido { get; set; }
        public Nullable<decimal> vvt { get; set; }
        public Nullable<decimal> vvc { get; set; }
        public Nullable<decimal> vvi { get; set; }
        public Nullable<decimal> impostopredial { get; set; }
        public Nullable<decimal> impostoterritorial { get; set; }
        public string natureza { get; set; }
        public Nullable<decimal> areaconstrucao { get; set; }
        public Nullable<decimal> testadaprinc { get; set; }
        public Nullable<decimal> valortotalparc { get; set; }
        public Nullable<decimal> valortotalunica { get; set; }
        public Nullable<decimal> valortotalunica2 { get; set; }
        public Nullable<decimal> valortotalunica3 { get; set; }
        public Nullable<short> qtdeparc { get; set; }
        public Nullable<decimal> txexpparc { get; set; }
        public Nullable<decimal> txexpunica { get; set; }
        public Nullable<decimal> areaterreno { get; set; }
        public Nullable<decimal> fatorcat { get; set; }
        public Nullable<decimal> fatorped { get; set; }
        public Nullable<decimal> fatorsit { get; set; }
        public Nullable<decimal> fatorpro { get; set; }
        public Nullable<decimal> fatortop { get; set; }
        public Nullable<decimal> fatordis { get; set; }
        public Nullable<decimal> fatorgle { get; set; }
        public Nullable<decimal> agrupamento { get; set; }
        public Nullable<decimal> fracaoideal { get; set; }
        public Nullable<decimal> aliquota { get; set; }
        public Nullable<byte> cpf { get; set; }
        public Nullable<byte> carne_web { get; set; }
    }
}
