//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class logradouro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public logradouro()
        {
            this.mobiliario = new HashSet<mobiliario>();
        }
    
        public int codlogradouro { get; set; }
        public Nullable<int> codtipolog { get; set; }
        public Nullable<int> codtitlog { get; set; }
        public string nomelogradouro { get; set; }
        public Nullable<System.DateTime> dataofic { get; set; }
        public string numofic { get; set; }
        public string endereco { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mobiliario> mobiliario { get; set; }
    }
}
