//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class mei
    {
        public int codigo { get; set; }
        public System.DateTime datainicio { get; set; }
        public Nullable<System.DateTime> datafim { get; set; }
    }
}
