//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class mobiliario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mobiliario()
        {
            this.mobiliarioevento = new HashSet<mobiliarioevento>();
            this.mobiliarioproprietario = new HashSet<mobiliarioproprietario>();
            this.mobiliarioatividadeiss = new HashSet<mobiliarioatividadeiss>();
        }
    
        public int codigomob { get; set; }
        public Nullable<short> dvmob { get; set; }
        public string razaosocial { get; set; }
        public string nomefantasia { get; set; }
        public Nullable<int> codlogradouro { get; set; }
        public Nullable<short> numero { get; set; }
        public string complemento { get; set; }
        public Nullable<short> codbairro { get; set; }
        public Nullable<short> codcidade { get; set; }
        public string siglauf { get; set; }
        public string cep { get; set; }
        public string homepage { get; set; }
        public Nullable<short> horario { get; set; }
        public Nullable<System.DateTime> dataabertura { get; set; }
        public string numprocesso { get; set; }
        public Nullable<System.DateTime> dataprocesso { get; set; }
        public Nullable<System.DateTime> dataencerramento { get; set; }
        public string numprocencerramento { get; set; }
        public Nullable<System.DateTime> dataprocencerramento { get; set; }
        public string inscestadual { get; set; }
        public string cnpj { get; set; }
        public string cpf { get; set; }
        public Nullable<short> isencao { get; set; }
        public Nullable<int> codatividade { get; set; }
        public string ativextenso { get; set; }
        public Nullable<float> areatl { get; set; }
        public Nullable<byte> codigoaliq { get; set; }
        public Nullable<System.DateTime> datainicialdesc { get; set; }
        public Nullable<System.DateTime> datafinaldesc { get; set; }
        public Nullable<float> percdesconto { get; set; }
        public Nullable<float> capitalsocial { get; set; }
        public string nomeorgao { get; set; }
        public Nullable<int> codprofresp { get; set; }
        public string numregistroresp { get; set; }
        public Nullable<short> qtdesocio { get; set; }
        public Nullable<short> qtdeempregado { get; set; }
        public Nullable<short> respcontabil { get; set; }
        public string rgresp { get; set; }
        public string orgaoemisresp { get; set; }
        public string nomecontato { get; set; }
        public string cargocontato { get; set; }
        public string fonecontato { get; set; }
        public string faxcontato { get; set; }
        public string emailcontato { get; set; }
        public byte vistoria { get; set; }
        public Nullable<short> qtdeprof { get; set; }
        public string rg { get; set; }
        public string orgao { get; set; }
        public string nomelogradouro { get; set; }
        public Nullable<byte> simples { get; set; }
        public Nullable<byte> regespecial { get; set; }
        public Nullable<byte> alvara { get; set; }
        public Nullable<System.DateTime> datasimples { get; set; }
        public Nullable<byte> isentotaxa { get; set; }
        public Nullable<byte> mei { get; set; }
        public string horarioext { get; set; }
        public Nullable<byte> isseletro { get; set; }
        public Nullable<System.DateTime> dispensaiedata { get; set; }
        public string dispensaieproc { get; set; }
        public Nullable<System.DateTime> dtalvaraprovisorio { get; set; }
        public string senhaiss { get; set; }
        public Nullable<byte> insctemp { get; set; }
        public Nullable<byte> horas24 { get; set; }
        public Nullable<byte> isentoiss { get; set; }
        public Nullable<byte> bombonieri { get; set; }
        public Nullable<byte> emitenf { get; set; }
        public Nullable<byte> danfe { get; set; }
        public Nullable<int> imovel { get; set; }
        public string sil { get; set; }
        public Nullable<bool> substituto_tributario_issqn { get; set; }
        public Nullable<bool> individual { get; set; }
        public string ponto_agencia { get; set; }
        public Nullable<bool> cadastro_vre { get; set; }
        public Nullable<bool> liberado_vre { get; set; }
    
        public virtual bairro bairro { get; set; }
        public virtual logradouro logradouro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mobiliarioevento> mobiliarioevento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mobiliarioproprietario> mobiliarioproprietario { get; set; }
        public virtual horariofunc horariofunc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mobiliarioatividadeiss> mobiliarioatividadeiss { get; set; }
    }
}
