//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class mobiliarioatividadeiss
    {
        public int codmobiliario { get; set; }
        public short codtributo { get; set; }
        public int codatividade { get; set; }
        public byte seq { get; set; }
        public short qtdeiss { get; set; }
        public decimal valoriss { get; set; }
    
        public virtual mobiliario mobiliario { get; set; }
    }
}
