//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class mobiliarioproprietario
    {
        public int codmobiliario { get; set; }
        public int codcidadao { get; set; }
        public Nullable<int> principal { get; set; }
    
        public virtual cidadao cidadao { get; set; }
        public virtual mobiliario mobiliario { get; set; }
    }
}
