//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class mobiliarioevento
    {
        public int codmobiliario { get; set; }
        public short codtipoevento { get; set; }
        public short seqevento { get; set; }
        public Nullable<System.DateTime> dataevento { get; set; }
        public string numprocevento { get; set; }
        public Nullable<System.DateTime> dataprocevento { get; set; }
        public Nullable<short> tipocalculo { get; set; }
    
        public virtual mobiliario mobiliario { get; set; }
    }
}
