//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class numdocumento
    {
        public int numdocumento1 { get; set; }
        public Nullable<System.DateTime> datadocumento { get; set; }
        public Nullable<short> codbanco { get; set; }
        public string codagencia { get; set; }
        public Nullable<decimal> valorpago { get; set; }
        public Nullable<decimal> valortaxadoc { get; set; }
        public Nullable<byte> isentomj { get; set; }
        public Nullable<decimal> percisencao { get; set; }
        public Nullable<short> tipodoc { get; set; }
        public string emissor { get; set; }
        public Nullable<decimal> valorguia { get; set; }
        public Nullable<bool> registrado { get; set; }
    }
}
