//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class sil
    {
        public int SID { get; set; }
        public int codigo { get; set; }
        public string sil1 { get; set; }
        public string protocolo { get; set; }
        public Nullable<System.DateTime> data_emissao { get; set; }
        public Nullable<System.DateTime> data_validade { get; set; }
        public Nullable<float> area_imovel { get; set; }
    }
}
