//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_inter_empr_snacional_giss
    {
        public decimal COD_CLIENTE { get; set; }
        public decimal NUM_CADASTRO { get; set; }
        public decimal INSCRICAO { get; set; }
        public System.DateTime DATA_INICIO { get; set; }
        public Nullable<System.DateTime> DATA_FIM { get; set; }
        public decimal CNPJ { get; set; }
        public string STATUS { get; set; }
        public string CNAE { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> DATA_DESCARTE { get; set; }
        public string OBS_DESCARTE { get; set; }
        public Nullable<decimal> EXERCICIO { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public string CONTROLE { get; set; }
    }
}
