//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class vre_licenciamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vre_licenciamento()
        {
            this.vre_pergunta = new HashSet<vre_pergunta>();
        }
    
        public int empresa_id { get; set; }
        public int solicitacao_Id { get; set; }
        public int orgao { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<bool> Risco { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> Data_Emissao { get; set; }
        public Nullable<System.DateTime> Data_Vencimento { get; set; }
    
        public virtual vre_empresa vre_empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vre_pergunta> vre_pergunta { get; set; }
    }
}
