//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class vre_declaracao
    {
        public int empresa_id { get; set; }
        public int solicitacao_id { get; set; }
        public int orgao { get; set; }
        public int declaracao_id { get; set; }
    }
}
