//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class vre_atividade
    {
        public int Id { get; set; }
        public string cnae { get; set; }
        public bool principal { get; set; }
        public bool exercida { get; set; }
    
        public virtual vre_empresa vre_empresa { get; set; }
    }
}
