//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class vre_empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vre_empresa()
        {
            this.vre_atividade = new HashSet<vre_atividade>();
            this.vre_licenciamento = new HashSet<vre_licenciamento>();
        }
    
        public int id { get; set; }
        public string razao_social { get; set; }
        public string cnpj { get; set; }
        public Nullable<System.DateTime> data_abertura { get; set; }
        public Nullable<byte> porte { get; set; }
        public string numero_registro { get; set; }
        public Nullable<byte> tipo_registro { get; set; }
        public Nullable<byte> tipo_mei { get; set; }
        public string cpf_responsavel { get; set; }
        public string nome_responsavel { get; set; }
        public string fone_contato1 { get; set; }
        public string fone_contato2 { get; set; }
        public string email_contato { get; set; }
        public string setor_quadra_lote { get; set; }
        public string tipo_logradouro { get; set; }
        public string nome_logradouro { get; set; }
        public Nullable<int> numero_imovel { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string uf { get; set; }
        public string cep { get; set; }
        public Nullable<double> area_estabelecimento { get; set; }
        public string nome_proprietario { get; set; }
        public string email_proprietario { get; set; }
        public string fone_proprietario { get; set; }
        public string nome_responsavel_uso { get; set; }
        public string fone_responsavel_uso { get; set; }
        public Nullable<double> area_total { get; set; }
        public Nullable<byte> pavimentos { get; set; }
        public Nullable<byte> contiguo { get; set; }
        public Nullable<byte> outros_usos { get; set; }
        public Nullable<byte> classif_CRC_PJ { get; set; }
        public string numero_CRC_PJ { get; set; }
        public string cnpj_contador { get; set; }
        public string tipo_CRC_PF { get; set; }
        public string numero_CRC_PF { get; set; }
        public string uf_CRC_PF { get; set; }
        public string cpf_contador { get; set; }
        public string nome_arquivo { get; set; }
        public Nullable<System.DateTime> data_importacao { get; set; }
        public Nullable<byte> classif_CRC_PF { get; set; }
        public string tipo_CRC_PJ { get; set; }
        public string uf_CRC_PJ { get; set; }
        public string situacao { get; set; }
        public Nullable<int> codreduzido { get; set; }
        public Nullable<System.DateTime> data_emissao { get; set; }
        public Nullable<System.DateTime> data_validade { get; set; }
        public string protocolo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vre_atividade> vre_atividade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vre_licenciamento> vre_licenciamento { get; set; }
    }
}
